a=int(input("Enter values:"))
b=int(input("Enter b value:"))
print("Addition",a+b)
print("sub",a-b)
print(a+b)
print("Added lines to new local")
print("Added by line git hub")
print("Collaborator Added")
